### ISSUE TITLE
5.Simulator web service. Getting Error in postman Get request ----- http://localhost:9003/v1/simulations

### ISSUE THREAD

**Issue by srinathreddy4** [microsoft/MCW-IoT-and-the-Smart-City#55]
[ERROR][2020-05-09 13:41:10.310][WebService.6bd1ab2d-8ed5-4d2b-ad2f-5f5d814b56c4][Simulations.cs:452:TryToStartDevicesCreationAsync] Failed to create bulk-device-creation job, { ExceptionFullName = Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.ExternalDependencyException, ExceptionMessage = Job quota exceeded, retry later, StackTrace =    at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Devices.CreateListUsingJobsAsync(IEnumerable`1 deviceIds) in C:\MCW-IoT-and-the-Smart-City\Hands-on lab\Lab-files\DeviceSimulation\Services\Devices.cs:line 515
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Simulations.TryToStartDevicesCreationAsync(String simulationId, IDevices devices) in C:\MCW-IoT-and-the-Smart-City\Hands-on lab\Lab-files\DeviceSimulation\Services\Simulations.cs:line 443, Source = Microsoft.Azure.IoTSolutions.DeviceSimulation.Services, Data = System.Collections.ListDictionaryInternal, InnerException = { ExceptionFullName = Microsoft.Azure.Devices.Common.Exceptions.JobQuotaExceededException, ExceptionMessage = Job quota has been exceeded, StackTrace =    at Microsoft.Azure.Devices.HttpClientHelper.ExecuteAsync(HttpClient httpClient, HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isMappedToException, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.HttpClientHelper.PostAsync[T1,T2](Uri requestUri, T1 entity, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.IotHub.RegistryManagerWrapper.ImportDevicesAsync(String containerUri, String inputBlobName) in C:\MCW-IoT-and-the-Smart-City\Hands-on lab\Lab-files\DeviceSimulation\Services\IotHub\RegistryManagerWrapper.cs:line 118
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Devices.CreateListUsingJobsAsync(IEnumerable`1 deviceIds) in C:\MCW-IoT-and-the-Smart-City\Hands-on lab\Lab-files\DeviceSimulation\Services\Devices.cs:line 509, Source = Microsoft.Azure.Devices, Data = System.Collections.ListDictionaryInternal, InnerException =  } }

**Comment by codingbandit** [comment]
Hi @srinathreddy - it looks like at this time you were receiving quota errors. Please retry as this is an error resulting from the Azure service (and not an issue with the source code).

**Comment by srinathreddy4** [comment]
Do I need to increase service limits in my Subscriptions ?

**Comment by codingbandit** [comment]
Please retry first and let me know how it goes.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no further comments from opener.  @srinathreddy4 please test and reopen if needed.
